#   _   _      _           _        _____ _     _
# | \ | |    | |         | |      / ____| |   (_)
# |  \| | ___| |__  _   _| | __ _| (___ | |__  _ _ __  ___
# | . ` |/ _ \ '_ \| | | | |/ _` |\___ \| '_ \| | '_ \/ __|
# | |\  |  __/ |_) | |_| | | (_| |____) | | | | | |_) \__ \
# |_| \_|\___|_.__/ \__,_|_|\__,_|_____/|_| |_|_| .__/|___/
#                                               | |
#                                               |_|

# =============== NEBULASHIPS CONFIG =============== #

Commands:
  COOLDOWN: 5000 # You do NOT want this to be too low, definitely not 0. This will avoid database spam and anything else. Most commands have something to do with the database, players should not have to use them repetitively.
