name: NebulaCore
version: '${project.version}'
main: net.nebulacraft.nebulacore.NebulaCore
api-version: '1.20'

description: "Spacecraft implementation for NebulaCraft."
authors: [Skullians, AstralSyntax, Nebs, ProGamingDK]

depend: [ packetevents ]

commands:
  nebulacore:
    usage: /<command>
